// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBovdTEsKkptu-n1A9FmXgdcJ7-_SajZJY',
    appId: '1:252614473099:web:b156024a141c437128eb8e',
    messagingSenderId: '252614473099',
    projectId: 'logolda',
    authDomain: 'logolda.firebaseapp.com',
    storageBucket: 'logolda.firebasestorage.app',
    measurementId: 'G-QV8JSNK8V6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTOSGNaFN2kekgW_5I5aX6NsMhbTT8ctc',
    appId: '1:252614473099:android:cf50f56691653c5f28eb8e',
    messagingSenderId: '252614473099',
    projectId: 'logolda',
    storageBucket: 'logolda.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtzKKswTVZV13V83QMXdogZzKvyVcHPWw',
    appId: '1:252614473099:ios:de24bceebeab580828eb8e',
    messagingSenderId: '252614473099',
    projectId: 'logolda',
    storageBucket: 'logolda.firebasestorage.app',
    iosBundleId: 'com.example.logolda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtzKKswTVZV13V83QMXdogZzKvyVcHPWw',
    appId: '1:252614473099:ios:de24bceebeab580828eb8e',
    messagingSenderId: '252614473099',
    projectId: 'logolda',
    storageBucket: 'logolda.firebasestorage.app',
    iosBundleId: 'com.example.logolda',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBovdTEsKkptu-n1A9FmXgdcJ7-_SajZJY',
    appId: '1:252614473099:web:2ddd69ac2cb5fa2328eb8e',
    messagingSenderId: '252614473099',
    projectId: 'logolda',
    authDomain: 'logolda.firebaseapp.com',
    storageBucket: 'logolda.firebasestorage.app',
    measurementId: 'G-S7K5R439Y3',
  );
}
